### ISSUE TITLE
New Maintainer?

### ISSUE THREAD

**Issue by Bouni** [coandco/pywinauto#1]
Hi,

are you the new Maintainer of this project?
I really want to use it but if it is no longer maintained, as it seemed to me until i found this github repo, i don't want to waste time on a dead project.

**Comment by coandco** [comment]
I suppose it depends on how you define 'maintainer'.  I created this GitHub repository because there were some fixes I wanted to make to the project for my personal use and, as you said, the original Google Code repository seems to have gone silent.  If nothing else, I'm certainly amenable to accepting issues and patches from people interested in the project.  Does that answer your question?

**Comment by Bouni** [comment]
Hi,

sounds good to me. Thanks for your efforts!
